### PR TITLE
Convert recipe to noarch:python

### PR DESCRIPTION
**Pull request by dopplershift**
Should also take care of getting it available for Python 3.7.

### CODE REVIEW

**Comment by dopplershift** [comment]
@ocefpaf It looks like you closed the bot's PR to do this...remember why?

**Comment by ocefpaf** [comment]
I don't remember buy we need to look for entrypoints, 2to3 or other bad
setup.py practices that may break noarch. I'll take a better look
tomorrow.

**Comment by dopplershift** [comment]
I'm guessing this is the problem, a `scripts=` line in the setup.

https://github.com/sphinx-gallery/sphinx-gallery/blob/6d0a0a69134f557b49023e734169ba6a47dbefda/setup.py#L33

**Comment by ocefpaf** [comment]
> I'm guessing this is the problem, a scripts= line in the setup.

That was probably it.

**Comment by ocefpaf** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
