### PR TITLE
Update to latest version.

### PR DESCRIPTION
**Pull request by QuLogic**

### CODE REVIEW

**Comment by QuLogic** [comment]
I don't know what's up with AppVeyor; not really related to my change, I think.

**Comment by pelson** [comment]
@conda-forge-admin, please rerender

**Comment by pelson** [comment]
LGTM. cc @conda-forge/sphinx-gallery

**Comment by jakirkham** [comment]
Maybe we need more maintainers here?

xref: https://github.com/conda-forge/sphinx-gallery-feedstock/pull/10

**Pull request merged**
